using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CardDatabase : MonoBehaviour
{
    public static List<Card> cardList = new List<Card>(); //I use static for best compatability between scripts.

    void Awake()
    {
        cardList.Add(new Card(0, "Ninguno", 0, 0, "Ninguna", "Ninguno", "Ninguno", Resources.Load<Sprite>("Empty Image"), Resources.Load<Sprite>("Empty Image"), Resources.Load<Sprite>("Empty Image")));
                                                                         //Neutral Units
        //Hero Units
        cardList.Add(new Card(1, "Jaqen H'ghar", 8, 12, "Un hombre no tiene nombre, y sin embargo, mil nombres. Maestro de sombras y cambiante como el viento, Jaqen H'ghar sirve al Dios de Muchos Rostros, equilibrando la balanza de la vida y la muerte con una precisión inquietante.","Héroe", "Elimina la carta con más poder del campo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Jaqen H'ghar"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("E3")));
        cardList.Add(new Card(2, "Oberyn Martell", 11, 1, "Conocido en todo Poniente como la Víbora Roja, Oberyn Martell es un guerrero feroz.Su presencia en el campo de batalla es tanto un espectáculo como una sentencia de muerte, manchada por el toque mortal de su lanza envenenada.", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Oberyn Martell"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(3, "El Perro", 11, 1, "Sandor Clegane, conocido como 'El Perro', es la encarnación de la ferocidad y el conflicto interno.Su habilidad en combate es legendaria, igualada solo por su profundo desprecio hacia su hermano, Gregor 'La Montaña' Clegane.", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("El Perro"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(4, "Varys", 3, 1, "Varys, conocido como 'La Araña', es el Consejero de los Rumores del Trono de Hierro. Su red de espías se extiende por todo el mundo conocido, y su influencia y sus conspiraciones lo convierten en uno de los jugadores más peligrosos en el juego de tronos.", "Héroe", "Roba una carta del mazo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Varys"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(5, "Petyr Baelish", 3, 1, "Petyr Baelish, conocido como 'Meñique', es Consejero de la Moneda del Trono de Hierro. Es el epítome del ascenso a través de la astucia y la manipulación. Desde sus humildes comienzos hasta convertirse en uno de los consejeros más influyentes del reino, su ambición no conoce límites.", "Héroe", "Juega una carta de aumento en la fila correspondiente. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Petyr Baelish"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E1")));
        //Silver Units
        cardList.Add(new Card(6, "Gorrión Supremo", 0, 1, "Líder de la Fe Militante, surge como un símbolo de esperanza para los oprimidos en los tiempos turbulentos de los Siete Reinos. Con su fervor religioso y su compromiso con la justicia divina, desafía abiertamente el poder de la nobleza y la corona.", "Plata", "Justicia Divina: Rogamos misericordia al Padre y al Guerrero para que nos den su bendición y hagan de este combate una batalla justa, igualando el poder de todas las unidades del campo.", Resources.Load<Sprite>("High Sparrow"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E8")));
        cardList.Add(new Card(7, "Nymeria Arena", 9, 12, "Ninguna", "Plata", "Elimina la carta con menor poder del enemigo.", Resources.Load<Sprite>("Nym"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("E4")));
        cardList.Add(new Card(8, "Brienne of Tarth", 11, 1, "Se une a la Guardia Arcoiris de Renly Baratheon luego de derrotar a Ser Loras Tyrell en combate singular. Escolta a Catelyn Stark luego de que Stannis asesinara a Renly con magia negra. Su espada, Oathkeeper, es un testamento de su compromiso con su deber.", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Brienne"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(9, "Beric Dondarrion", 7, 1, "Una vez Señor de Blackhaven, ahora es conocido como el Señor Resucitado. Después de haber sido revivido múltiples veces por el poder del Señor de la Luz, Beric ha renacido con un propósito mayor: defender los ideales de justicia y proteger a los indefensos.", "Plata", "Elimina la carta con menor poder del campo enemigo.", Resources.Load<Sprite>("Beric"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E4")));
        cardList.Add(new Card(10, "Thoros de Myr", 7, 1, "Sacerdote guerrero del Señor de la Luz, icónico por su espada flameante en la pelea contra la revelión Greyjoy. Aunque ebrio la mayoría del tiempo, combate las tinieblas en Poniente junto a Beric Dondarrion a quien ha resucitado varias veces.", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Thoros"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        //Special Cards
        cardList.Add(new Card(11, "Ventisca", 0, 0, "Una tempestad de invierno se desata sobre el campo de batalla, congelando el aire y paralizando a las tropas enemigas. Los soldados luchan por mantener el calor mientras la ventisca helada debilita sus fuerzas.", "Clima", "Reduce a 1 el poder de todas las unidades de Combate Cercano de ambos jugadores.", Resources.Load<Sprite>("Blizzard"), Resources.Load<Sprite>("Empty Image"), Resources.Load<Sprite>("Cold")));
        cardList.Add(new Card(12, "Niebla Cegadora", 0, 0, "Una niebla oscura y densa se cierne sobre el campo de batalla, envolviendo a los arqueros enemigos en un manto asfixiante. Su visión se ve limitada y su precisión comprometida, mientras luchan por discernir los blancos a través de la densa neblina.", "Clima", "Reduce a 1 el poder de todas las unidades de Combate a Distancia de ambos jugadores.", Resources.Load<Sprite>("Fog"), Resources.Load<Sprite>("Empty Image"), Resources.Load<Sprite>("FogIcon")));
        cardList.Add(new Card(13, "Tempestad", 0, 0, "Una tormenta oscura y aterradora se forma sobre el campo de batalla, con vientos violentos, relámpagos y una lluvia intensa que destruye todo a su paso. Las unidades de asedio enemigas sufren grandes daños bajo el impacto de la tormenta.", "Clima", "Reduce a 1 el poder de todas las unidades de Asedio de ambos jugadores.", Resources.Load<Sprite>("Storm"), Resources.Load<Sprite>("Empty Image"), Resources.Load<Sprite>("Rain")));
        cardList.Add(new Card(14, "Despejado", 0, 0, "El sol brilla radiante en el cielo despejado, disipando las nubes y restaurando la paz en el campo de batalla. La brisa suave y reconfortante barre el caos anterior, dejando un ambiente tranquilo y sereno en su lugar.", "Clima", "Elimina todas las cartas tipo Clima del campo.", Resources.Load<Sprite>("Clear"), Resources.Load<Sprite>("Empty Image"), Resources.Load<Sprite>("Clear Skies")));
        cardList.Add(new Card(15, "Cuerno Legendario", 0, 4, "Un cuerno misterioso con inscripciones antiguas. Muchos dicen que es el Cuerno del Invierno, otros lo cren el Cuerno del Dragón. Solo se conoce que al hacerlo sonar estremece el campo de batalla, infundiendo un fervor indomable en las tropas.", "Aumento", "Duplica el poder de todas las unidades de la fila. Sólo se puede jugar una carta de aumento por ronda.", Resources.Load<Sprite>("Buff"), Resources.Load<Sprite>("Empty Image"), Resources.Load<Sprite>("Horn")));
        cardList.Add(new Card(16, "Bufón", 0, 123, "Supuesto caballero de los Siete Reinos, Ser Dontos Hollard se convirtió en Bufón real cuando Sansa Stark logró salvarle la vida de la crueldad del Rey Joffrey. Sin habilidad alguna como guerrero ni como bufón, se convierte en un simple peón a ser sacrificado por el bien mayor.", "Señuelo", "Intercambia esta carta por cualquier unidad en tu lado del campo para regresarla a la mano.", Resources.Load<Sprite>("Jester"), Resources.Load<Sprite>("Empty Image"), Resources.Load<Sprite>("Decoy")));
                                                                          //The North
        //Leader
        cardList.Add(new Card(17, "Robb Stark", 0, 5, "          \"Rey en el Norte\"\nEl rey Robb Stark es el hijo primogénito de Lord Eddard Stark y Lady Catelyn Tully, siendo desde su nacimiento el heredero de Invernalia y el Norte.", "Líder", "Las tropas del Norte son inmunes ante el efecto de la carta \"Ventisca\".", Resources.Load<Sprite>("Robb Stark"), Resources.Load<Sprite>("The North Sigil"), Resources.Load<Sprite>("Empty Image")));
        //Hero Units
        cardList.Add(new Card(18, "Viento Gris", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Viento Gris"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(19, "Brandon Stark", 6, 3, "Ninguna", "Héroe", "Roba una carta del mazo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Bran"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(20, "Verano", 10, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Verano"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(21, "Catelyn Stark", 2, 3, "Ninguna", "Héroe", "Juega una carta de aumento en la fila correspondiente. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Catelyn"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E1")));
        cardList.Add(new Card(22, "Brynden Tully", 9, 12, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Blackfish"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(23, "Theon Greyjoy", 10, 2, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Theon"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(24, "Ramsey Snow", 8, 2, "Ninguna", "Héroe", "Elimina la carta con más poder del campo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Ramsey"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("E3")));
        //Silver Units
        cardList.Add(new Card(25, "Maester Luwin ", 0, 3, "Ninguna", "Plata", "Pelea Justa: Iguala el poder de todas las cartas del campo.", Resources.Load<Sprite>("Luwin"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E8")));
        cardList.Add(new Card(26, "Ser Rodrick Cassel", 8, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Rodrick"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(27, "Jeyne Westerling", 4, 3, "Ninguna", "Plata", "Juega la carta \"Despejado\" del mazo.", Resources.Load<Sprite>("Jeyne"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E2")));
        cardList.Add(new Card(28, "Edmure Tully", 7, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Edmure"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(29, "Greatjon Umber", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Greatjon"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(30, "Roose Bolton", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Roose Bolton"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(31, "Lyanna Mormont", 6, 1, "Ninguna", "Plata", "Juega una carta de aumento en la fila correspondiente.", Resources.Load<Sprite>("Lyanna Mormont"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E1")));
        cardList.Add(new Card(32, "Panda", 10, 1, "No se sabe mucho aparte del evidente hecho de que es un Panda. Se rumorea que vino de la Isla del Oso. Es un luchador feroz y defiende el norte con colmillos y garras.", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Panda"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(33, "Osha", 8, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Osha"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(34, "Hodor", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Hodor"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(35, "Porta-Estandarte", 5, 1, "Ninguna", "Plata", "Juega una carta de aumento en la fila correspondiente.", Resources.Load<Sprite>("PEN"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E1")));
        cardList.Add(new Card(36, "Soldado Norteño", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("SoldadoN"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(37, "Infantería Norteña", 5, 1, "Ninguna", "Plata", "Multiplica su ataque por la cantidad de veces que esta carta se repite en el campo propio.", Resources.Load<Sprite>("InfanteríaN"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E6")));
        cardList.Add(new Card(38, "Arquero Norteño", 5, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("ArqueroN"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(39, "Caballero Norteño", 8, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("CaballeroN"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(40, "Ariete", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Ariete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(41, "Torre de Asedio", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Torre de Asedio"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(42, "Trebuquete", 7, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Trebuquete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(43, "Catapulta", 8, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Catapulta"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(44, "Balista", 10, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Balista"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
                                                                       //The Crown
        //Leader
        cardList.Add(new Card(45, "Joffrey Baratheon", 0, 5, "Ninguna", "Líder", "Ninguno", Resources.Load<Sprite>("Joffrey"), Resources.Load<Sprite>("The Crown Sigil"), Resources.Load<Sprite>("Empty Image")));
        //Hero Units
        cardList.Add(new Card(46, "Tywin Lannister", 5, 1, "Ninguna", "Héroe", "Iguala el poder de todas las cartas del campo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Tywin"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E8")));
        cardList.Add(new Card(47, "Cersei Lannister", 4, 3, "Ninguna", "Héroe", "Elimina la carta con más poder del campo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Cersei"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E3")));
        cardList.Add(new Card(48, "Ser Jaime Lannister", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Jaime"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(49, "Tyrion Lannister", 6, 1, "Ninguna", "Héroe", "Fuego Valirio: Limpia la fila del campo enemigo con menos unidades. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Tyrion"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E7")));
        cardList.Add(new Card(50, "Ser Gregor Clegane", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("La Montaña"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(51, "Ser Loras Tyrell", 10, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Loras"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(52, "Ser Bronn", 9, 12, "Este simple mercenario ha escalado las filas hasta convertirse en una figura formidable en los intrincados juegos de poder de Poniente. Aunque su moralidad pueda ser cuestionable, su astucia y habilidades en el campo de batalla son indiscutibles.", "Héroe", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Bronn"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("Empty Image")));
        //Silver Units
        cardList.Add(new Card(53, "Ser Meryn Trant", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Meryn Trant"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(54, "Ser Arys Oakheart", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Arys Oakheart"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(55, "Ser Kevan Lannister", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Kevan"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(56, "Ser Lancel Lannister", 6, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Lancel"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(57, "Maester Pycell", 0, 3, "Ninguna", "Plata", "Roba una carta del mazo.", Resources.Load<Sprite>("Pycell"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(58, "Ser Garlan Tyrell", 10, 1, "Ninguna", "Plata", "Juega una carta de aumento en la fila correspondiente.", Resources.Load<Sprite>("Garlan Tyrell"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E1")));
        cardList.Add(new Card(59, "Ser Ilyn Payne", 8, 1, "Ninguna", "Plata", "Justicia del Rey: Elimina la carta con menor poder del campo enemigo.", Resources.Load<Sprite>("Ilyn Payne"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E4")));
        cardList.Add(new Card(60, "Podrick Payne", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Podrick"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(61, "Piromante", 3, 3, "Ninguna", "Plata", "Fuego Valirio: Limpia la fila del campo enemigo con menos unidades.", Resources.Load<Sprite>("Piromante"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E7")));
        cardList.Add(new Card(62, "Shagga", 8, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Shagga"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(63, "Porta-Estandarte", 5, 1, "Ninguna", "Plata", "Juega una carta de aumento en la fila correspondiente.", Resources.Load<Sprite>("PEL"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E1")));
        cardList.Add(new Card(64, "Capas Doradas", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Capas Doradas"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(65, "Infantería Lannister", 5, 1, "Ninguna", "Plata", "Multiplica su ataque por la cantidad de veces que esta carta se repite en el campo propio.", Resources.Load<Sprite>("InfanteríaL"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E6")));
        cardList.Add(new Card(66, "Arquero Lannister", 5, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("ArqueroL"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(67, "Caballero del Rey", 8, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("CaballeroC"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(68, "Ariete", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Ariete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(69, "Torre de Asedio", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Torre de Asedio"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(70, "Trebuquete", 7, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Trebuquete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(71, "Catapulta", 8, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Catapulta"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(72, "Balista", 10, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Balista"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
                                                                       //Targaryen
        //Leader
        cardList.Add(new Card(73, "Daenerys Targaryen", 0, 5, "Ninguna", "Líder", "Ninguno", Resources.Load<Sprite>("Dany"), Resources.Load<Sprite>("Targaryen Sigil"), Resources.Load<Sprite>("Empty Image")));
        //Hero Units
        cardList.Add(new Card(74, "Khal Drogo", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Drogo"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(75, "Ser Jorah Mormont", 9, 1, "Ninguna", "Héroe", "Roba una carta del mazo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Jorah"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(76, "Ser Barristan Selmy", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Barristan"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(77, "Daario Naharis", 10, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Daario"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(78, "Gusano Gris", 9, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Gusano"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(79, "Drogon", 11, 3, "Ninguna", "Héroe", "Fuego de Dragón: Limpia la fila del campo enemigo con menos unidades. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Drogon"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E7")));
        cardList.Add(new Card(80, "Rhaegal", 10, 3, "Ninguna", "Héroe", "Fuego de Dragón: Limpia la fila del campo enemigo con menos unidades. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Rhaegal"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E7")));
        cardList.Add(new Card(81, "Viserion", 10, 3, "Ninguna", "Héroe", "Fuego de Dragón: Limpia la fila del campo enemigo con menos unidades. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Viserion"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E7")));
        //Silver Units
        cardList.Add(new Card(82, "Missandei", 0, 3, "Ninguna", "Plata", "Roba una carta del mazo.", Resources.Load<Sprite>("Missandei"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(83, "Aggo", 8, 12, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Aggo"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(84, "Rakharo", 8, 12, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Rakharo"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(85, "Jhogo", 8, 12, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Jhogo"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(86, "Guerrero Dothraki", 7, 12, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Dothraki1"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(87, "Arquero Dothraki", 7, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Dothraki2"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(88, "Inmaculado", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Inmaculado"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(89, "Hero", 8, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Hero"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(90, "Mercenario SH", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Mercenario SH"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(91, "Arquero SH", 5, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Arquero SH"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(92, "Porta-Estandarte", 5, 1, "Ninguna", "Plata", "Juega una carta de aumento en la fila correspondiente.", Resources.Load<Sprite>("PET"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E1")));
        cardList.Add(new Card(93, "Soldado Targaryen", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("SoldadoT"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(94, "Infantería Targaryen", 5, 1, "Ninguna", "Plata", "Multiplica su ataque por la cantidad de veces que esta carta se repite en el campo propio.", Resources.Load<Sprite>("InfanteríaT"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E6")));
        cardList.Add(new Card(95, "Arquero Mercenario", 5, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("ArqueroM"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(96, "Ariete", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Ariete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(97, "Torre de Asedio", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Torre de Asedio"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(98, "Trebuquete", 7, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Trebuquete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(99, "Catapulta", 8, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Catapulta"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(100, "Balista", 10, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Balista"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
                                                                       //Greyjoy
        //Leader
        cardList.Add(new Card(101, "Balon Greyjoy", 0, 5, "Ninguna", "Líder", "Ninguno", Resources.Load<Sprite>("Balon"), Resources.Load<Sprite>("Greyjoy Sigil"), Resources.Load<Sprite>("Empty Image")));
        //Hero Units
        cardList.Add(new Card(102, "Victarion Greyjoy", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Victarion"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(103, "Euron Greyjoy", 10, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Euron"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(104, "Aeron Greyjoy", 6, 1, "Ninguna", "Héroe", "Intervención Divina: Rezamos al dios Ahogado para que invoque una nieba sin precedente que ciege las tropas enemigas. Juega la carta \"Niebla Cegadora\" del mazo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Aeron"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E2")));
        cardList.Add(new Card(105, "Asha Greyjoy", 9, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Asha"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(106, "Theon Greyjoy", 10, 2, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Theon2"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(107, "Victoria de Hierro", 11, 3, "Ninguna", "Héroe", "Cañones del Victoria: Limpia la fila del campo enemigo con menos unidades. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Victoria"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E7")));
        cardList.Add(new Card(108, "Silencio", 10, 3, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Silencio"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(109, "Gran Kraken", 10, 3, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Gran Kraken"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        //Silver Units
        cardList.Add(new Card(110, "Sacerdote Ahogado", 2, 3, "Ninguna", "Plata", "Roba una carta del mazo.", Resources.Load<Sprite>("Sacerdote"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(111, "Saqueador Isleño", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Saqueador1"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(112, "Capitán de Navío", 8, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Capitán"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(113, "Explorador Isleño", 6, 12, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("ExploradorIB"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(114, "Arquero Isleño", 5, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("ArqueroIB"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(115, "Tripulación Silenciosa", 6, 3, "Ninguna", "Plata", "Multiplica su ataque por la cantidad de veces que esta carta se repite en el campo propio.", Resources.Load<Sprite>("Tripulación1"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E6")));
        cardList.Add(new Card(116, "Berserker Isleño", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Berserker"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(117, "Dagmer Barbarrota", 7, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Dagmer"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(118, "Marinero de Saltcliffe", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Marinero"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(119, "Saqueador Veterano", 7, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Saqueador2"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(120, "Ingeniero de Pyke", 4, 3, "Ninguna", "Plata", "Juega una carta de aumento en la fila correspondiente.", Resources.Load<Sprite>("Ingeniero"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E1")));
        cardList.Add(new Card(121, "Barcoluengo", 8, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Barcoluengo"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(122, "Tripulación del Victoria", 6, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Tripulación2"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(123, "Arquero de Harlaw", 5, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("ArqueroIB2"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(124, "Ariete", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Ariete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(125, "Torre de Asedio", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Torre de Asedio"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(126, "Trebuquete", 7, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Trebuquete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(127, "Catapulta", 8, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Catapulta"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(128, "Balista", 10, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Balista"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));    
                                                                       //Night's Watch
        //Leader
        cardList.Add(new Card(129, "Jon Snow", 0, 5, "Ninguna", "Líder", "Ninguno", Resources.Load<Sprite>("Jon"), Resources.Load<Sprite>("Crow Sigil"), Resources.Load<Sprite>("Empty Image")));
        //Hero Units
        cardList.Add(new Card(130, "Ghost", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Ghost"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(131, "Qhorin Mediamano", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Qhorin"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(132, "Ygritte", 10, 2, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Ygritte"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(133, "Tormund Matagigantes", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Tormund"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(134, "Samwell Tarly", 4, 1, "Ninguna", "Héroe", "Slayer: Elimina la carta con menos poder del campo enemigo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Sam"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E4")));
        cardList.Add(new Card(135, "Maester Aemon", 0, 3, "Ninguna", "Héroe", "Roba una carta del mazo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Aemon"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(136, "Benjen Stark", 11, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Benjen"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(137, "Mance Rayder", 9, 1, "Ninguna", "Héroe", "Juega la carta \"Ventisca\" del mazo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Viserion"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E2")));
        //Silver Units
        cardList.Add(new Card(138, "Casaca de Matraca", 8, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Bones"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(139, "Grenn", 7, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Grenn"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(140, "Pypar", 6, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Pyp"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(141, "Eddison", 7, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Edd"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(142, "Wun Wun", 11, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Wun Wun"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(143, "Mamut", 11, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Mamut"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(144, "Sigorn", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Sigorn"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(145, "Val", 6, 2, "Ninguna", "Plata", "Elimina la carta con menos poder del campo enemigo.", Resources.Load<Sprite>("Val"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("E4")));
        cardList.Add(new Card(146, "Orell", 7, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Orell"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(147, "Explorador", 6, 1, "Ninguna", "Plata", "Multiplica su ataque por la cantidad de veces que esta carta se repite en el campo propio.", Resources.Load<Sprite>("Explorador"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E6")));
        cardList.Add(new Card(148, "Constructor", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Constructor"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(149, "Mayordomo", 3, 3, "Ninguna", "Plata", "Roba una carta del mazo.", Resources.Load<Sprite>("Mayordomo"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(150, "Saqueador Thennita", 7, 12, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("SaqueadorW"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(151, "Satin", 5, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Satin"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(152, "Ariete", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Ariete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(153, "Torre de Asedio", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Torre de Asedio"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(154, "Trebuquete", 7, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Trebuquete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(155, "Catapulta", 8, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Catapulta"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(156, "Balista", 10, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Balista"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
                                                                       //Baratheon
        //Leader
        cardList.Add(new Card(157, "Stannis Baratheon", 0, 5, "Ninguna", "Líder", "Ninguno", Resources.Load<Sprite>("Stannis"), Resources.Load<Sprite>("Baratheon Sigil"), Resources.Load<Sprite>("Empty Image")));
        //Hero Units
        cardList.Add(new Card(158, "Melisandre", 4, 3, "Ninguna", "Héroe", "Fuego de R'hllor: Limpia la fila del campo enemigo con menos unidades. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Melissandre"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E7")));
        cardList.Add(new Card(159, "Ser Davos Seaworth", 6, 1, "Ninguna", "Héroe", "Roba una carta del mazo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Davos"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(160, "Salladhor Saan", 9, 3, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Salladhor"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(161, "Sombra de Stannis", 11, 1, "Ninguna", "Héroe", "Elimina la carta con más poder del campo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Sombra"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E3")));
        cardList.Add(new Card(162, "Selyse Florent", 2, 3, "Ninguna", "Héroe", "Intervención Divina: Rezamos a R'hllor para que invoque una tormenta sin precedente que destruya las tropas enemigas. Juega la carta \"Tempestad\" del mazo. Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Selyse"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E2")));
        cardList.Add(new Card(163, "Ser Godry Farring", 10, 1, "Ninguna", "Héroe", "Esta carta no es afectada por efectos de ninguna otra carta.", Resources.Load<Sprite>("Godry"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        //Silver Units
        cardList.Add(new Card(164, "Ser Clayton Suggs", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Clayton"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(165, "Ser Richard Horpe", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Richard"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(166, "Ser Justin Massey", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Justin"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(167, "Ser Axell Florent", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Axell"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(168, "Ser Rolland Storm", 9, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Rolland"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(169, "Arquero de R'hllor", 8, 2, "Ninguna", "Plata", "Flecha de R'hllor: Elimina la carta con menos poder del campo enemigo.", Resources.Load<Sprite>("ArqueroB"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("E4")));
        cardList.Add(new Card(170, "Maester Cressen", 0, 3, "Ninguna", "Plata", "Roba una carta del mazo.", Resources.Load<Sprite>("Cressen"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E5")));
        cardList.Add(new Card(171, "Mercenario Braavosi", 7, 12, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("MercenarioB"), Resources.Load<Sprite>("Sword and Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(172, "Soldado Baratheon", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("SoldadoB"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(173, "Arquero Braavosi", 6, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("ArqueroB1"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(174, "Porta-Estandarte", 5, 1, "Ninguna", "Plata", "Juega una carta de aumento en la fila correspondiente.", Resources.Load<Sprite>("PEB"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E1")));
        cardList.Add(new Card(175, "Pirata de Lys", 5, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Pirata"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(176, "Caballero del Rey", 8, 1, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("CaballeroB"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(177, "Infantería Baratheon", 5, 1, "Ninguna", "Plata", "Multiplica su ataque por la cantidad de veces que esta carta se repite en el campo propio.", Resources.Load<Sprite>("InfanteríaB"), Resources.Load<Sprite>("Sword"), Resources.Load<Sprite>("E6")));
        cardList.Add(new Card(178, "Arquero Baratheon", 5, 2, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("ArqueroB"), Resources.Load<Sprite>("Bow"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(179, "Acólito de R'hllor", 3, 3, "Ninguna", "Plata", "Fuego de R'hllor: Limpia la fila del campo enemigo con menos unidades.", Resources.Load<Sprite>("Acólito"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("E7")));
        cardList.Add(new Card(180, "Ariete", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Ariete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(181, "Torre de Asedio", 5, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Torre de Asedio"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(182, "Trebuquete", 7, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Trebuquete"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(183, "Catapulta", 8, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Catapulta"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
        cardList.Add(new Card(184, "Balista", 10, 3, "Ninguna", "Plata", "Esta carta no tiene ninguna abilidad especial.", Resources.Load<Sprite>("Balista"), Resources.Load<Sprite>("Siege"), Resources.Load<Sprite>("Empty Image")));
    }
}
